#!/bin/bash
#
# Usage ./RamDisk 'RAM Disk' 4
# 'RAM Disk' - name of mounted disk
# 4 - size of disk in gigabytes
#

NAME="RAM Disk"
SIZE=7812500 #4 GB (4 000 000 000 / 512 sector size)

while [ ! -d /Volumes ]
do
    echo "waiting..."
    sleep 1
done

if [ -n "$1" ]; then NAME="$1"; fi
if [ -n "$2" ]; then SIZE=$(($2 * 1000000000 / 512)); fi

if [ ! -d /Volumes/"$NAME" ]; then
    echo "creating $NAME with $SIZE sectors..."
    diskutil erasevolume HFS+ "$NAME" `hdiutil attach -nomount ram://$SIZE` 
fi

exit
